language: ruby

services:
  - rabbitmq

env:
  - JRUBY_OPTS="--dev -Xcext.enabled=false -Xcompile.invokedynamic=false"

rvm:
  - jruby-1.7.16
  - jruby-head
  - 2.1.5

bundler_args: --deployment --binstubs --jobs=3 --retry=3

cache: bundler

jdk:
  - openjdk7
  - openjdk6
  - oraclejdk7

matrix:
  exclude:
    - rvm: 2.1.5
      jdk: openjdk7
    - rvm: 2.1.5
      jdk: openjdk6
    - rvm: 2.1.5
      jdk: oraclejdk7
    - rvm: 2.1.5
      jdk: oraclejdk7
    - rvm: jruby-head
      jdk: openjdk6
  allow_failures:
    - rvm: jruby-head
      jdk: openjdk7
    - rvm: jruby-head

sudo: false

before_script: cp config/worker.example.yml config/worker.yml

script: bin/rspec spec

matrix:
  allow_failures:
    - rvm: jruby-head
