language: ruby

services:
  - rabbitmq

env:
  - JRUBY_OPTS="--dev -Xcext.enabled=false -Xcompile.invokedynamic=false"

rvm:
  - jruby-1.7.16
  - ruby-2.1.5
#- jruby-head

#temporary fix, see https://github.com/joshk/sshjr/issues/3
before_install:
  - rvm @global do gem uninstall -aIx bundler '>1.10.0' --force || true
  - rvm @global do gem install bundler -v '1.9.4'
  - bundle --version

bundler_args: --deployment --binstubs --jobs=3 --retry=3

cache: bundler

jdk:
  - openjdk7
  - oraclejdk7

matrix:
  exclude:
    - rvm: 2.1.5
      jdk: openjdk7
    - rvm: 2.1.5
      jdk: openjdk6
    - rvm: 2.1.5
      jdk: oraclejdk7
    - rvm: 2.1.5
      jdk: oraclejdk7
  allow_failures:
    - rvm: jruby-head
      jdk: openjdk7

sudo: false

before_script: cp config/worker.example.yml config/worker.yml

script: bin/rspec spec

matrix:
  allow_failures:
    - rvm: jruby-head
